export MASTER_PORT=29504
torchrun --nproc_per_node=1 --master_port=$MASTER_PORT main_mar.py \
    --model mar_base \
    --diffloss_d 6 \
    --diffloss_w 1024 \
    --vae_path pretrained_models/vae/kl16.ckpt \
    --buffer_size 64 \
    --vae_embed_dim 16 \
    --vae_stride 16 \
    --patch_size 1 \
    --batch_size 1 \
    --eval_bsz 16 \
    --img_size 512 \
    --resume output_Resume \
    --evaluate \
    --paired_test \
    --hr_data_path /root/autodl-tmp/zanding/CelebA-Test-400/HQ \
    --lr_data_path /root/autodl-tmp/zanding/CelebA-Test-400/LQ \
    --use_lr_inject \
    --use_rope \
    --use_dynamic_maskgit \
    --conf_method cosine \
    --conf_threshold 0.9 \
    --conf_pmin 0.05 \
    --use_mse_loss \
    --conf_window '100:0:10' \
    --output_dir Evaluate_Resume_Cosine_0.9_0.05_100:0_16_0.8-1.0
